#!/usr/bin/perl
use v5.20.0;
use warnings;
use lib 'lib';
use Sieve '-all';

say comment(lines(<<'END'))->as_sieve;
END

my $rule = lines(
  1,
  words("a", 2, "c"),
  '',
  [ qw(this is indented), [ qw(even more) ] ],
  '',
  cond("some-test", lines("foo", "bar")),
  cond("blort", lines("this", "runs"), lines("the", "else", "block")),
  3,
);

say $rule->as_sieve;
say comment($rule)->as_sieve;

my $json = JSON::MaybeXS->new->pretty->canonical->encode({
  masks => 0,
  tea   => { ladygrey => 5, oolong => 0 },
  soup  => [ qw( clam clam clam corn ) ],
});

say words("do thing", textblock($json))->as_sieve;

